#!/bin/bash
#PBS -N hello_world
#PBS -q workq
#PBS -l select=1:ncpus=1:mem=1gb
#PBS -l walltime=00:05:00
#PBS -o example_hello_world.out
#PBS -e example_hello_world.err

echo "Hola desde $(hostname), corriendo como trabajo $PBS_JOBID"
echo "Iniciado a las: $(date)"
echo "Tengo ${PBS_NUM_PPN:-1} CPU(s) y esta cantidad de memoria disponible:"
free -h | head -2
sleep 5
echo "Terminado a las: $(date)"
