#!/bin/bash
# Write nextflow.config for THIS cluster from your site.conf.
#   ./make_config.sh
# Re-run it after changing site.conf. The generated file is not tracked by git.

cd "$(dirname "$0")" || exit 1
source ../lib/edu.sh || exit 1

case "$CONTAINER_RUNTIME" in
    singularity) ENGINE="singularity" ;;
    *)           ENGINE="apptainer" ;;
esac
QUEUE_LINE="// queue = 'your_queue'   (site.conf has no EDU_QUEUE: the default queue is used)"
[ -n "${EDU_QUEUE:-}" ] && QUEUE_LINE="queue = '$EDU_QUEUE'"

cat > nextflow.config <<CONF
// Generated by make_config.sh from ../site.conf on $(date +%F). Do not edit by hand.

params {
    samples   = '$DATA_DIR/samples/samples.tsv'
    ref       = '$DATA_DIR/ref/genome.fasta'
    outdir    = '$WORKDIR/08_nextflow/results'
    sif_dir   = '$SIF_CACHE'
    // how many samples to process (SAM files are big; raise it when you are comfortable)
    n_samples = 3
}

workDir = '$WORKDIR/08_nextflow/nf_work'

process {
    // 'pbspro' works for OpenPBS and PBS Professional. Torque uses 'pbs'.
    executor = 'pbspro'
    $QUEUE_LINE

    withName: 'FASTP'             { container = "\${params.sif_dir}/fastp.sif" }
    withName: 'MINIMAP2'          { container = "\${params.sif_dir}/minimap2.sif" }
    withName: 'SAMTOOLS_SORT'     { container = "\${params.sif_dir}/samtools.sif" }
    withName: 'SAMTOOLS_FLAGSTAT' { container = "\${params.sif_dir}/samtools.sif" }
    withName: 'SEQKIT_STATS'      { container = "\${params.sif_dir}/seqkit.sif" }

    // Retry once if the task was killed from outside (exit codes 137 / 143 / 265 / 271: memory or
    // walltime limit, or a node problem); any other error stops the pipeline. To also give the
    // retry more memory, write e.g.  memory { 2.GB * task.attempt }  inside a process.
    errorStrategy = { task.exitStatus in [137, 143, 271, 265] ? 'retry' : 'terminate' }
    maxRetries    = 1
}

$ENGINE {
    enabled    = true
    autoMounts = true
    runOptions = '--bind $(edu_binds)'
}

executor {
    // don't flood the scheduler, and don't poll it every second
    queueSize    = 20
    pollInterval = '15 sec'
    // On shared filesystems a finished job's exit file can appear late. If Nextflow
    // marks finished jobs as failed, uncomment (and raise) the next line.
    // exitReadTimeout = '270 sec'
}
CONF
mkdir -p "$WORKDIR/08_nextflow"
echo "wrote $(pwd)/nextflow.config"
echo "Next:  nextflow run main.nf -resume        (or:  qsub run_nextflow.pbs)"
